### ISSUE TITLE
Couldn't run the app

### ISSUE THREAD

**Issue by sathishpanduga** [Deathangel908/djangochat#1]
When I run the app on windows (Python 3.4), using below command

> python manage.py start_tornado 
> or 
> python manage.py runserver 0.0.0.0:8000

It throws below error 

[chat.context_processors.add_user_name
"TypeError: can only concatenate tuple (not "list") to tuple"]

Instructions should be more clear so that it would be helpful to django beginners like me

**Comment by Deathangel908** [comment]
Hi I fixed this with commit https://github.com/Deathangel908/djangochat/commit/e4dea2b8b16f8165dd8b5522917fe0331de4a67d . It had to deal with django 1.9. They have changed a lot in this revision. Check if again please, and tell me if you have any other issues. Have a sunny day!

**Comment by akoidan** [comment]
Hi, it had to do with django 1.9. Django uses list now instead of tuple for context_processors. Fixed with https://github.com/Deathangel908/djangochat/commit/d25992581a0f6f98f3668b88b9b82eb7c14d9d07 .Let me know if you have other issues
