### ISSUE TITLE
Skip Registration

### ISSUE THREAD

**Issue by Gelmo** [Deathangel908/djangochat#18]
Is there a simple way to run this without the requirement to login? My intended use is a single room, iframed in a webpage, allowing any visitors to join the chat easily.

**Comment by akoidan** [comment]
Not at the moment. I will probably add this in the future, but unfortunately I don't have time right now for it.
You're also welcome to create a pull request. The fastest implementation you may use is:
 Add the flag to https://github.com/akoidan/pychat/blob/master/fe/development.json and check in registration page https://github.com/akoidan/pychat/blob/master/fe/src/components/singup/MainPage.vue if it's set to true. If so proceed with the registration logic with random name and password https://github.com/akoidan/pychat/blob/master/fe/src/utils/api.ts#L90-L96 
Note that you will need to disable capthca in the settings, this is already disabled by default.

**Comment by Gelmo** [comment]
Excellent,
Thank you for the insightful comment. If I get around to working on this I'll be sure to create a PR.

**Comment by akoidan** [comment]
Implemented with [Added auto_registration](https://github.com/akoidan/pychat/commit/05c902031a1a698a034bf66964045ba131639048) . You want to build frontend with [AUTO_REGISTRATION = true](https://github.com/akoidan/pychat/blob/master/fe/development.json#L10)

**Comment by akoidan** [comment]
Implemented with [Added auto_registration](https://github.com/akoidan/pychat/commit/05c902031a1a698a034bf66964045ba131639048) . You want to build frontend with [AUTO_REGISTRATION = true](https://github.com/akoidan/pychat/blob/master/fe/development.json#L10)

Don't forget that you might need to turn off [same-origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) policy if it's on in settings.

You can use [docker](https://github.com/akoidan/pychat#build-docker) to build the image. In this case you want to edit `fe/production.json`
