### ISSUE TITLE
Cannot run with python3

### ISSUE THREAD

**Issue by faraz117** [Deathangel908/djangochat#20]
settings_base.py", line 216, in <module>
    'context_processors': global_settings.TEMPLATE_CONTEXT_PROCESSORS + [username_processor]
AttributeError: module 'django.conf.global_settings' has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'

When i run it locally with python 2 i get 404 .. Any clues would be helpful.

**Comment by akoidan** [comment]
What django version are you using? Are you using venv? You should use requirements.txt to install dependencies, it has `django==1.9.12` as a dependency that has `TEMPLATE_CONTEXT_PROCESSORS`. Check `/site-packages/django/conf/global_settings.py` for `TEMPLATE_CONTEXT_PROCESSORS` variable declaration

If you don't need a development environment you can use docker, it's described in Docker section in README.md

**Comment by faraz117** [comment]
Hi sorry i was using Django 2.2.1 . Yes i am using venv . I downgraded to django==1.9.12 but i am still getting Import Error: Cannot import name 'update_contenttypes'.

I am using the development environment since i plan to contribute and understand the project . 
Also when i run it with python2 .
I am able to run tornado (In a seperate process ). i have executed manage.py runserver ( in a separate process ). And in the fe/ i "yarn run dev" in a separate process . But i still get a 404 while accessing the server. I can load the frontend at :8080 but it has a connection error. 

Sorry for the long list of questions . I am just starting with django and web apps. If this is cluttered i can open an other issue for these questions or simply email you.

**Comment by akoidan** [comment]
It's likely you have some dependencies issue. global packages conflict with local. Try to use venv. Follow the [Bootstrap files section](https://github.com/akoidan/pychat#bootstrap-files) . There's no way you would get a django version issue if you used `venv` in the first place

 - Create virtualEnv virtualenv --system-site-packages .venv and activate it: source .venv/bin/activate
 - Install python packages with pip install -r requirements.txt

**Comment by faraz117** [comment]
Ok i will start with a fresh clone then . Thanks .
