### ISSUE TITLE
Running local development environment django 404 not found

### ISSUE THREAD

**Issue by faraz117** [Deathangel908/djangochat#21]
I am running the development setup on ubuntu 18. I performed the following steps

1. Install OS packages depending on your OS type (Runs successfully)
2. Bootstrap files (Runs successfully)
3. Follow instructions in fe/README.md 
I did yarn install and yarn run dev and i let this run in a seperate terminal.
4. Start services and check if it works
4.1 Ran mysql
4.2 Ran redis-server
4.3 manage.py start tornado ( Runs in a seperate terminal)
4.4 python manage.py runsslserver 0.0.0.0:8000

So i can access 0.0.0.0:8000 as django page not found
0.0.0.0:8888 returns "Can upgrade to only websocket"
0.0.0.0:8080 runs the front end but it has connection error. I cannot sign up or anything.

Which features can i expect to see locally ? How can i make this work locally ? Do i need to edit development.json in the fe ?

**Comment by akoidan** [comment]
- `0.0.0.0:8888`  listens websocket, so it's totaly fine that for http request tornado returns `Can upgrade to only websocket`
 - Check if https://localhost:8080` server is running via browser, it should return django debug page. you probably would need to add this server to browser exception while you're opening it, since it has self-signed certificate.
 - After you add the certificate frontned won't complain about connection error.

If it doesn't work, please add some logs from tornado/django process. Also observe `Networks tab` and see check requests/responses. If it doesn't work we can communicate via skype/telegram/viber and I will help you via teamviewer.

**Comment by faraz117** [comment]
So i am running the https://localhost:8080. I am getting the frontend . And the security exception is also added . The django server is printing this ..

Exception happened during processing of request from ('127.0.0.1', 58474)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/faraz/pychat/pychat/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 99, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/home/faraz/pychat/pychat/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 164, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2292)

I have also used ./download_content.sh generate_certificate but still no luck. Below is the output of networks tab.
![Screenshot](https://user-images.githubusercontent.com/8335983/56058139-e31bbc00-5d60-11e9-8287-96a5dca346d9.png)

Also my skype id is farazbhatti117

**Comment by akoidan** [comment]
You don't need to generate certificate for development server, pip package `django-sslserver` is used to runssl and it provide certificates that are used by django along with tornado. For vue frontend webpack-dev-server generates new certificate every time you run this command.

**Comment by faraz117** [comment]
Alright . Thanks for the help ! It works now !
