### ISSUE TITLE
Uncaught (in promise) Error: Current browser doesnt support offline notifications

### ISSUE THREAD

**Issue by akoidan** [Deathangel908/djangochat#25]
chrome push notifications are not longer available though android

**Comment by akoidan** [comment]
Google deprecated GCM in favor to FCM.

**Comment by akoidan** [comment]
https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications
https://pypi.org/project/pywebpush/
https://stackoverflow.com/a/54996207/3872976
https://github.com/firebase/quickstart-js/blob/master/messaging/README.md

**Comment by dayan2222** [comment]
After running a command python manage.py start_tornado I'm getting this error. 
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django

I already installed Django but it is not removing. Help me, please!

**Comment by akoidan** [comment]
Fixed
