### ISSUE TITLE
Using Postgresql

### ISSUE THREAD

**Issue by sah-anshu** [Deathangel908/djangochat#37]
Hi
I can see the complete documentation is built on MySQL, can you please provide me help, if i want to use Postgresql as Database. 

Thanks

**Comment by akoidan** [comment]
Hi

You can use docker provided image so you don't need to configure anything. If you want to use native setup I recommend to use MySQL. Cause this question sounds to me, I have only Ruby, how can I run python code.

 MySQL and Postgres are completely different databases that use different syntaxt (which only from the first look seems the same). In theory  django ORM should abstract you from those implementation layer (db api), but there are corner cases like different unique limitation for string/different type of atomic operation handling/some db-specific hacks , like [this one](https://github.com/akoidan/pychat/blob/31dedf60cbada3d27ec7b02c47935327af693093/chat/utils.py#L67)

If won't just magically work out of the box, be ready to face some challenges. if you're ready for them you can follow [official django postgres guide ](https://docs.djangoproject.com/en/2.2/ref/databases/#postgresql-notes)

 - you will need to install any django supported postgres driver, like [this one](https://www.psycopg.org/)
 - and change `DATABASES['default']['ENGINE'] =  'django.db.backends.postgresql'`

**Comment by sah-anshu** [comment]
Thanks I shall try this.
