### ISSUE TITLE
Can't setup development server

### ISSUE THREAD

**Issue by saran-gangster** [Deathangel908/djangochat#47]
Hey man this is a nice project all in one chat application. Although I found some bugs and code improvements and also I want to add more features <br>

So I setup development server as referred in the read me <br>
1.cloned the project 
2.Installed python with pip.
Added pip and python to PATH variable.(tried in python 3.8 and 3.9)
3.Installed redis (latest)
4.Installed mysql.installed python's mysqlclient. 
5.Added bash commands to path 
6.Installed nvm.

Did all steps in [bootstrap files](https://github.com/akoidan/pychat#bootstrap-files)
Also [build fronted](https://github.com/akoidan/pychat#build-frontend)

Then I started mysql and redis-server

Started webSocket listener: python manage.py start_tornado (works fine) 
After this nothing works 
''''
Open in browser https://127.0.0.1:8080.
Add self signed ssl certificate provided by django-sslserver to browser exception. For chrome you can enable invalid certificates for localohost in chrome://flags/#allow-insecure-localhost. Or for others open https://localhost:8888 and https://localhost:8000. Where 8888 comes from start_tornado.py

''''

**Comment by saran-gangster** [comment]
I can give you further details of my problem
Please help me!!!

**Comment by akoidan** [comment]
@saran-gangster please provide errors or describe the situation in details. Which things exactly don't work.

**Comment by saran-gangster** [comment]
Sorry for late reply

when i go to https://localhost:8888/
```
Traceback (most recent call last):
  File "/home/Desktop/pychat/backend/venv/lib/python3.8/site-packages/tornado/web.py", line 1489, in _execute
    result = self.prepare()
  File "/home/Desktop/pychat/backend/venv/lib/python3.8/site-packages/tornado/web.py", line 2224, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```
i started using ``` python manage.py start_tornado```
```
System check identified some issues:

WARNINGS:
chat.Room: (models.W027) MySQL does not support check constraints.
        HINT: A constraint won't be created. Silence this warning if you don't care about it.
tornado server started at 0.0.0.0:8888
None [05:17:24:398;None;start_tornado:72]: Starting pinger
None [05:18:49:407;None;iostream:1331]: SSL Error on 11 ('127.0.0.1', 39170): [SSL: HTTP_REQUEST] http request (_ssl.c:1124)
None [05:18:54:311;None;iostream:1331]: SSL Error on 11 ('127.0.0.1', 39178): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1124)
None [05:18:54:366;None;web:2063]: 404 GET / (127.0.0.1) 14.21ms
None [05:18:54:414;None;web:2063]: 404 GET /favicon.ico (127.0.0.1) 0.76ms
None [05:22:24:400;None;global_redis:83]: Pinging clients: p{"action": "ping", "time": 1608520944400, "handler": "ws"}
```
i enabled insecure extension on chrome flags
https://localhost:8000/ is not working


i am new to node js so i don't know what is happening ask me if you want any details 
kindly help me!!

**Comment by akoidan** [comment]
`https://localhost:8888/` is API url. You need to open https://localhost:8000. As README describes. Did you follow https://github.com/akoidan/pychat#build-frontend ?

> Webpack-dev-server is used for development purposes with hot reloading, every time you save the file it will automatically apply. This doesn't affect node running files, only watching files. So files like builder.js or development.json aren't affected. To run dev-server use yarn run dev

**Comment by saran-gangster** [comment]
yes 
https://localhost:8000/  also doesn't work

**Comment by akoidan** [comment]
What do you mean by `https://localhost:8000/ also doesn't work` ? 
 - is `yarn run dev` process running? 
 - Does it have any errors? 
 - Is port `8000` opened? 
 - what chrome says when you open `https://localhost:8000/ `
 - Did you accept self-sign certificate?
