### ISSUE TITLE
P2p Messaging

### ISSUE THREAD

**Issue by SyedAnasShah** [Deathangel908/djangochat#49]
Where are you storing the P2p enabled messages in table? I mean the name of that table. Is the chat encrypted?

**Comment by hostingseguro** [comment]
I think `p2p` messages are saved in localStorage and then are synchronized to establish the connection between the two sides.

**Comment by SyedAnasShah** [comment]
> I think `p2p` messages are saved in localStorage and then are synchronized to establish the connection between the two sides.

What if I login with a different device? I am also getting the previous messages. My concern is that where it is storing the p2p messages.?

**Comment by akoidan** [comment]
P2P messages are stored on [websql](https://github.com/akoidan/pychat/blob/2e770a588b4906da87592175afb178b3e62c3b4e/frontend/src/ts/classes/DatabaseWrapper.ts#L48) along with any other messages. When you logout logout [method](https://github.com/akoidan/pychat/blob/8812fa1e8e209cc17e528dc10cda2036961b407f/frontend/src/ts/classes/DefaultStore.ts#L995) is called, which [clearStorage](https://github.com/akoidan/pychat/blob/2e770a588b4906da87592175afb178b3e62c3b4e/frontend/src/ts/classes/DatabaseWrapper.ts#L98). Chat is fully secured.

**Comment by akoidan** [comment]
closing due to week of inactivity
