### ISSUE TITLE
Sometimes impossible to open menu with "edit message" item

### ISSUE THREAD

**Issue by ivictbor** [Deathangel908/djangochat#6]
Not sure why, sometimes default browser context menu appeared instead of message edit menu:

![image](https://cloud.githubusercontent.com/assets/1838656/21472880/42032e6a-caf6-11e6-9333-7c513d102289.png)

**Comment by akoidan** [comment]
This behaviour was explicity introduced to allow user to use native browser function for copying images. TO be specific allow user "copy image address"/"copy image url". Furthermore you can't edit the message after some period of time (currently 1min)
